import type { PassportData } from '@bpp/shared';

type Spec = [
  id: string,
  model: [id: string, name: string],
  mass: number,
  category: PassportData['generalInformation']['batteryCategory'],
  status: PassportData['generalInformation']['batteryStatus'],
  date: string,
  place: string,
  warranty: string,
  manufacturer: [name: string, id: string],
  chemistry: string,
  materials: string[],
  footprint: number,
];

const ELECTROLYTE = {
  substanceName: 'Lithium Hexafluorophosphate',
  chemicalFormula: 'LiPF6',
  casNumber: '21324-40-3',
};
const COBALT = { substanceName: 'Cobalt(II) oxide', chemicalFormula: 'CoO', casNumber: '1307-96-6' };
const LEAD = { substanceName: 'Lead', chemicalFormula: 'Pb', casNumber: '7439-92-1' };
const SULFURIC_ACID = { substanceName: 'Sulfuric acid', chemicalFormula: 'H2SO4', casNumber: '7664-93-9' };

const SPECS: Spec[] = [
  [
    'BP-2024-011',
    ['LM3-BAT-2024', 'GMC WZX1'],
    450,
    'EV',
    'Original',
    '2024-01-15',
    'Gigafactory Nevada',
    '8',
    ['Tesla Inc', 'TESLA-001'],
    'LiFePO4',
    ['Lithium', 'Iron'],
    850,
  ],
  [
    'BP-2024-012',
    ['NMC-811-P75', 'PowerCell 75'],
    520,
    'EV',
    'Original',
    '2024-02-20',
    'Wrocław, Poland',
    '8',
    ['LG Energy Solution', 'LGES-PL-02'],
    'NMC 811',
    ['Lithium', 'Nickel', 'Cobalt', 'Manganese'],
    1120,
  ],
  [
    'BP-2024-013',
    ['CATL-QL-3', 'Qilin CTP 3.0'],
    610,
    'EV',
    'Original',
    '2024-03-05',
    'Arnstadt, Germany',
    '10',
    ['CATL', 'CATL-DE-01'],
    'NMC 622',
    ['Lithium', 'Nickel', 'Cobalt', 'Graphite'],
    1340,
  ],
  [
    'BP-2024-014',
    ['BLD-BLADE-60', 'Blade 60'],
    395,
    'EV',
    'Original',
    '2024-04-18',
    'Szeged, Hungary',
    '8',
    ['BYD', 'BYD-HU-01'],
    'LiFePO4',
    ['Lithium', 'Iron', 'Phosphorus'],
    690,
  ],
  [
    'BP-2024-015',
    ['NVL-E48', 'Northvolt Voltpack Mobile'],
    280,
    'Industrial',
    'Original',
    '2024-05-09',
    'Skellefteå, Sweden',
    '12',
    ['Northvolt', 'NV-SE-01'],
    'NMC 622',
    ['Lithium', 'Nickel', 'Cobalt'],
    410,
  ],
  [
    'BP-2024-016',
    ['EB-LMT-36', 'UrbanRide 36V'],
    3.2,
    'LMT',
    'Original',
    '2024-06-12',
    'Ho Chi Minh City, Vietnam',
    '2',
    ['Samsung SDI', 'SDI-VN-03'],
    'NMC 532',
    ['Lithium', 'Nickel', 'Cobalt'],
    38,
  ],
  [
    'BP-2023-021',
    ['SLI-AGM-70', 'StartStop AGM 70Ah'],
    20.5,
    'SLI',
    'Original',
    '2023-09-30',
    'Hannover, Germany',
    '3',
    ['Clarios', 'CLR-DE-04'],
    'Lead-acid (AGM)',
    ['Lead', 'Antimony'],
    95,
  ],
  [
    'BP-2022-007',
    ['LM3-BAT-2022', 'GMC WZX0'],
    455,
    'Industrial',
    'Repurposed',
    '2022-07-11',
    'Gigafactory Nevada',
    '5',
    ['Tesla Inc', 'TESLA-001'],
    'NCA',
    ['Lithium', 'Nickel', 'Cobalt', 'Aluminium'],
    910,
  ],
  [
    'BP-2021-033',
    ['NMC-622-P60', 'PowerCell 60'],
    430,
    'EV',
    'Remanufactured',
    '2021-11-02',
    'Ochang, South Korea',
    '4',
    ['LG Energy Solution', 'LGES-KR-01'],
    'NMC 622',
    ['Lithium', 'Nickel', 'Cobalt', 'Manganese'],
    980,
  ],
  [
    'BP-2024-017',
    ['PT-18650-3S', 'PowerTool 18V'],
    0.65,
    'Portable',
    'Original',
    '2024-07-22',
    'Tianjin, China',
    '2',
    ['Panasonic Energy', 'PAN-CN-02'],
    'NCA',
    ['Lithium', 'Nickel', 'Cobalt'],
    9.5,
  ],
];

/** Ten realistic sample passports: the assignment's example plus a spread of categories and statuses. */
export const DEMO_PASSPORTS: PassportData[] = SPECS.map(
  ([
    id,
    [modelId, modelName],
    mass,
    category,
    status,
    date,
    place,
    warranty,
    [maker, makerId],
    chemistry,
    materials,
    footprint,
  ]) => ({
    generalInformation: {
      batteryIdentifier: id,
      batteryModel: { id: modelId, modelName },
      batteryMass: mass,
      batteryCategory: category,
      batteryStatus: status,
      manufacturingDate: date,
      manufacturingPlace: place,
      warrantyPeriod: warranty,
      manufacturerInformation: { manufacturerName: maker, manufacturerIdentifier: makerId },
    },
    materialComposition: {
      batteryChemistry: chemistry,
      criticalRawMaterials: materials,
      hazardousSubstances: chemistry.startsWith('Lead')
        ? [LEAD, SULFURIC_ACID]
        : materials.includes('Cobalt')
          ? [ELECTROLYTE, COBALT]
          : [ELECTROLYTE],
    },
    carbonFootprint: {
      totalCarbonFootprint: footprint,
      measurementUnit: 'kg CO2e',
      methodology: 'Life Cycle Assessment (LCA)',
    },
  }),
);
